
# Site settings
title: lggmonclar.github.io
email: lggmonclar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: lggmonclar
github_username:  lggmonclar

# Build settings
markdown: kramdown

highlighter: rouge

#plugins
plugins: [jekyll-paginate]

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


# collections:
#   portfolio:
#     output: true
#     permalink: /portfolio/:path/
#   poetry:
#     output: true
#     permalink: /poetry/:path/
